### ISSUE TITLE
Record Action 'Delete' makes a form... in a form. Invalid HTML

### ISSUE THREAD

**Issue by dreamingmind** [curlyjason/simpleblog#2]
Record action for Delete uses a postLink helper which makes a form. On the index page, these tools are already inside a form (<tr><td><form><table>this has the delete tool</table></form></td></tr>. Nested forms are not allowed.

A solution is to use a regular link, but delete only allows POST to prevent a casual user from typing a 'delete' url and killing a record.

This might be an ongoing problem, so an index page solution isn't going to be enough.

**Comment by dreamingmind** [comment]
Cake docs mention this problem:

This method creates a <form> element. So do not use this method inside an existing form. Instead you should add a submit button using Cake\View\Helper\FormHelper::submit()

I'm not sure how this would solve the problem. Is there some way to have a submit button modify the form post? We could have inline javascript that changed the form's target action. The postLink() method already depends on js, so this would be no worse.

I suppose, the worst case scenario for that choice would be having 'delete' do nothing in certain contexts like where there was some dynamic multi-record situation and we couldn't get outside the form (exactly like the index page).

If we weren't in a table/multi-record situation we could probably find a DOM pattern that would get the delete tool outside the record form.

I've been thinking about a way to do table-ish multi-record structures that use a grid system instead of tables because we could make those responsive. 

If you can figure out a responsive solution...

**Comment by dreamingmind** [comment]
Well, while writing that I figured out a solution.

<tr>   <td><form>
    <table>some record field inputs here</table>
</form></td>   <td>this has the delete tool</td>   </tr>

and it works fine

**Comment by curlyjason** [comment]
I like your basic solution. I'm trying to wrap my head around the grid in the base Cake css and try to find a way to reproduce CRUD pages in grid instead of table.
I'll let you know how I proceed.
