### ISSUE TITLE
CrudHelper config doesn't support all options

### ISSUE THREAD

**Issue by dreamingmind** [curlyjason/simpleblog#3]
The 'action' level only allows one path/action pair but the internal helper system can support many model, view and record settings.

Either the config can be beefed up or the Action Pattern objects can be created separate from the helper (and earlier in the controller action) then sent to the helper like CrudData, or the config process must be beefed up substantially.

Since the ActionPattern is a stand alone object with a full interface to modify its contents, it could easily be made early and sent to the helper just before rendering.

The default settings could them be moved into appController? or bootstrap?

Probably AppController. And beforeFilter could set the defaults just like it does for crudData. Then sub-class controllers could add their own settings and controller actions could put their finishing touches on the patterns.

**Comment by curlyjason** [comment]
I understand that this is solved by the incorporation of the setup in the beforeFilter on appController
