### ISSUE TITLE
CrudHelper needs to differentiate between Field type overrides and Action overrides

### ISSUE THREAD

**Issue by dreamingmind** [curlyjason/simpleblog#6]
Right now, the methods that support these two types of overrides are stored in the same class. Not good. The detection of the two types of overrides should route to an appropriate class for that type.

The field type alternates come into play through this sequence of events:

```
$this->CrudHelper->output(); // which calls
$this->CrudFields->output(); // which then uses FieldSetups if an override exists
```

The Action override happens in:

```
$this->CrudHelper->createFieldHandler($action);
// the default switch state then targets FieldSetups if an override exists
```

**Comment by curlyjason** [comment]
Are you thinking of an additional class (other than CrudHelper) for this?

**Comment by dreamingmind** [comment]
Don Drake:
    i don’t think so
    i’m thinking that, of the two places that shunt requests off to FeildSetups, one of them needs to name a different class, then we can move all the appropriate methods out of Fieldsetups and into the new class.
Curly Media:
    OK, I think I understand
    use FieldSetups for the, well, fields
Don Drake:
    hahhaa right!
Curly Media:
    And use, perhaps, ActionSetups for the actions
Don Drake:
    yes
Curly Media:
    Now I’m getting it. I forgot that basic level of abstraction that already existed.
